#!/bin/bash

# activa/desactiva un "modul" per una instacia
#

# falta validar millor els parametres que rep el script

EMACSLIB=~/.emacs.d/conf.d
INSTANCIES=$EMACSLIB/instances
INITD=$EMACSLIB/init.d
EMACS=/usr/bin/emacs
LISPDIRS="-L $EMACSLIB/site-lisp -L $EMACSLIB/my-lisp"
PROGRAMA=$(basename $0)

function get_instancies {
    local instancies

    for d in $INSTANCIES/* ; do
        dd=$(basename "$d")
        if [ -d "$d" -a "$dd" != "common" ] ; then
            instancies="$instancies $dd"
        fi
    done

    echo $instancies
}

function versionat_amb_svn {
    test -d $1/.svn
}

function help {
    echo "Gestiona moduls d'emacs."
    echo
    echo "* activar un mòdul:"
    echo "    $PROGRAMA (-e|--enable) modul NN (instancies|all)"
    echo
    echo "* desactivar un mòdul:"
    echo "    $PROGRAMA (-d|--disable) modul (instancies|all)"
    echo
    echo "* ajuda:"
    echo "    $PROGRAMA -h"
    exit 0
}

function activar_modul {
    local modul
    local nivel
    local instancia
    local i

    modul=$1
    shift
    if [ ! -f "$INITD/${modul}.el" ] ; then
        echo "El mòdul '${modul}.el' no existeix"
        exit -1
    fi

    if [ ! -f "$INITD/${modul}.elc" ] ; then
	    $EMACS --batch 										\
            --no-site-file 									\
            $LISPDIRS										\
	        --funcall batch-byte-compile "$INITD/${modul}.el"

        if [ $? -ne 0 ] ; then
            echo "Error compilant el mòdul '$modul'."
            exit -1
        fi
    fi

    nivell=$1
    shift
    # faltaria comprovar que es un valor numeric entre 0 i 99

    instancia=$@
    if [ "$instancia" == "all" ] ; then
        instancia=$(get_instancies)
    fi

    for i in $instancia ; do
        ln -s ../../../init.d/$modul.elc "$INSTANCIES/$i/init.d/$nivell-$modul.elc"
        if versionat_amb_svn "$INSTANCIES/$i/init.d" ; then
            svn add "$INSTANCIES/$i/init.d/$nivell-$modul.elc"
        fi
    done
}

function desactivar_modul {
    local modul
    local instancia
    local i

    modul=$1
    shift

    instancia=$@
    if [ "$instancia" == "all" ] ; then
        instancia=$(get_instancies)
    fi

    for i in $instancia ; do
        if versionat_amb_svn "$INSTANCIES/$i/init.d" ; then
            svn rm $INSTANCIES/$i/init.d/*-$modul.elc
        else
            rm -f $INSTANCIES/$i/init.d/*-$modul.elc
        fi
    done
}


case "$1" in
    -d|--disable)
        shift
        desactivar_modul $@
        ;;

    -e|--enable)
        shift
        activar_modul $@
        ;;

    -h)
        help
        ;;

    *)
        echo "Comando no reconegut '$1'."
        echo
        help
        ;;
esac
