(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 101 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
 '(cursor ((t (:background "orange"))))
 '(diff-added ((t (:inherit diff-changed-face :foreground "green"))))
 '(diff-changed ((t nil)))
 '(diff-file-header ((t (:background "blue" :weight bold))))
 '(diff-header ((((class color) (background dark)) (:background "blue"))))
 '(diff-removed ((t (:inherit diff-changed-face :foreground "red"))))
 '(font-lock-emphasized-face ((t (:foreground "yellow"))))
 '(font-lock-other-emphasized-face ((t (:foreground "red"))))
 '(highlight ((t (:background "dimgray" :foreground "white"))))
 '(mode-line ((t (:background "brown" :foreground "white" :box nil))))
 '(region ((t (:foreground "white" :background "darkcyan"))))
 '(rst-level-1-face ((t (:background "unspecified")))))

(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(TeX-auto-save t)
 '(TeX-parse-self t)
 '(TeX-printer-list (quote (("Local" "dvips %s -o; gv %s.ps" "lpq") ("lw") ("ps"))))
 '(ansi-color-for-comint-mode t)
 '(c-basic-offset 4)
 '(column-number-mode t)
 '(cperl-font-lock t)
 '(cperl-hairy t)
 '(cperl-indent-level 8)
 '(current-language-environment "UTF-8")
 '(default-frame-alist (quote ((foreground-color . "white") (background-color . "black") (menu-bar-lines . 0) (font . "monospace") (tool-bar-lines . 0))))
 '(display-time-mode t nil (time))
 '(ecb-options-version "2.27")
 '(ecb-source-path (quote ("~/zope/develop")))
 '(erc-insert-timestamp-function (quote erc-insert-timestamp-right))
 '(erc-server-coding-system (quote (latin-1 . latin-1)))
 '(erc-timestamp-format "[%H:%M]")
 '(erc-timestamp-right-column 0)
 '(erc-user-full-name "Alexis Roda")
 '(font-lock-maximum-decoration t)
 '(global-font-lock-mode t nil (font-lock))
 '(global-hl-line-mode t nil (hl-line))
 '(hl-line-face (quote highlight))
 '(indent-tabs-mode nil)
 '(inhibit-eol-conversion nil)
 '(inhibit-startup-screen t)
 '(lpr-command "lp")
 '(lpr-printer-switch "-d")
 '(mouse-buffer-menu-maxlen 25)
 '(mouse-buffer-menu-mode-mult 10)
 '(mouse-wheel-down-button 4 t)
 '(mouse-wheel-follow-mouse t)
 '(mouse-wheel-mode t nil (mwheel))
 '(mouse-wheel-scroll-amount (quote (1 5)))
 '(mouse-yank-at-point t)
 '(next-line-add-newlines nil)
 '(partial-completion-mode t nil (complete))
 '(pr-ps-printer-alist (quote ((default "lp" nil "-P" "HPLaserjet3005"))))
 '(printer-name "hp1220c")
 '(ps-n-up-printing 1)
 '(ps-printer-name "HPLaserJet3005")
 '(ps-printer-name-option "-d")
 '(ps-zebra-stripes nil)
 '(py-indent-offset 4)
 '(py-prepare-autopair-mode-p nil)
 '(py-shell-name "ipython")
 '(py-smart-indentation nil)
 '(safe-local-variable-values (quote ((encoding . utf-8))))
 '(scroll-bar-mode nil)
 '(scroll-preserve-screen-position t)
 '(scroll-step 1)
 '(show-trailing-whitespace nil)
 '(srctool-todo-ignore-directories (quote (".emacs~" "CVS" "RCS" ".svn" "epydoc")))
 '(srctool-todo-labels (quote ("@TODO:" "@FIXME:" "@NOTE:")))
 '(svn-status-verbose nil)
 '(tab-width 4)
 '(time-stamp-format "%a, %02d/%02m/%02y %02H:%02M:%02S")
 '(tool-bar-mode nil nil (tool-bar))
 '(tooltip-mode t nil (tooltip))
 '(transient-mark-mode t))

